version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
#    depends_on:
#      db:
#        condition: service_healthy
    command: >
      bash -c "poetry run uvicorn app:app --host 0.0.0.0 --port 8000"

#  db:
#    image: postgres:latest
#    container_name: db
#    volumes:
#      - postgres_storage:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./.docker/nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_storage: